### PR TITLE
Back button "disabled".

### PR DESCRIPTION
**Pull request by ivan-avalos**
I found that when you pressed the back button, you were able to go back to the system launcher. Now, when you press back button, launcher activity is launched again.

I would like to upload the apk to Google Play, what do you think? I was searching for an app like this yesterday, but I didn't find anything. So, this would be the simplest app available in Google Play. I have a license :)

### CODE REVIEW

**Comment by ruslangm** [comment]
@ivan-avalos That would be awesome!  
And I would be grateful if you leave a link on Github repository in app description in Google Play to support open source 😃

**Comment by ruslangm** [comment]
@ivan-avalos can you notice me when you will release it in Google Play? 
I will leave 5 stars review ⭐️ 😄

**Comment by ivan-avalos** [comment]
I've just uploaded app to Google Play Store. It will be available in about 1~2 hours.

**Comment by ivan-avalos** [comment]
We should add a license to the project. What do you think about GPLv3? Or LGPLv3? Or maybe BSD?
I would use GPLv3.

**Comment by ruslangm** [comment]
@ivan-avalos That’s a good choice! I think GPLv3 is completely suitable for us.

**Comment by ruslangm** [comment]
@ivan-avalos can you make a new pull request with updated Readme.md containing link on Google Play when it will be available?

**Comment by ivan-avalos** [comment]
It has been rejected by Google Play, I think I included some "offensive" terms. But I have removed them, and uploaded an update. App has support for API 26 (I think it was another reason to be rejected, because of new Terms and Conditions). I hope it's accepted now.

**Comment by ivan-avalos** [comment]
Success! 100%
https://play.google.com/store/apps/details?id=com.ruslan.androidlauncher

**Comment by ivan-avalos** [comment]
I will make the pull request now!

**Comment by ruslangm** [comment]
@ivan-avalos Great work man!

**Pull request merged**
